version: '3'
services:
  line:
    # image: localhost/linnil1/attendence_bot
    image: linnil1/att
    restart: always
    volumes:
      - ./:/app
    command: tail -f /dev/null
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:7-alpine
    restart: always
    volumes:
      - ./redis_data:/data
