version: '3'
services:
  line:
    image: linnil1/attendence_bot
    build: .
    ports:
      - 10101:10101
    restart: always
    volumes:
      - ./:/app
    command: python line.py
    depends_on:
      - redis

  redis:
    image: docker.io/library/redis:7-alpine
    restart: always
    volumes:
      - ./redis_data:/data
